/* ============================================================================
   Architecture Board Review — Question Bank (SAMPLE CONTENT)
   Replace / expand this array with your real exam questions any time.
   Each item: { id, cat, q, options:[A,B,C,D], answer:<0-3>, explain }
   cat must match one of the CATEGORIES ids below.
   ========================================================================== */

const SOURCES = [
  { id: "jpt", name: "JPT Learning Center", items: 1240 },
  { id: "ucj", name: "UC Jaguars Mock Exam", items: 860 },
];

const CATEGORIES = [
  { id: "struct", name: "Structural Conceptual Design", short: "Structural" },
  { id: "hist",   name: "History & Theory",             short: "History" },
  { id: "prac",   name: "Professional Practice",        short: "Practice" },
  { id: "util",   name: "Building Utilities",           short: "Utilities" },
  { id: "design", name: "Architectural Design",         short: "Design" },
  { id: "mats",   name: "Building Materials",           short: "Materials" },
];

const MODES = [
  { id: "normal", name: "Normal",        sub: "+1 correct",       blurb: "One point per correct answer. No penalty for wrong answers." },
  { id: "rw",     name: "Right \u2212 Wrong", sub: "+1 / \u22121", blurb: "One point per correct answer, minus one for every wrong answer. Blanks are zero." },
  { id: "timed",  name: "Timed",         sub: "45:00 clock",      blurb: "Scored like Normal, but the session is timed. It auto-submits when the clock runs out." },
];

const QUESTION_BANK = [
  /* ---------------- Structural Conceptual Design ---------------- */
  { id: "S01", cat: "struct", q: "Which structural system carries lateral loads primarily through axial forces in diagonal members rather than bending?",
    options: ["Moment-resisting frame", "Braced frame", "Flat-slab system", "Bearing-wall system"], answer: 1,
    explain: "Braced frames resist lateral loads through axial tension and compression in their diagonal bracing, making them stiffer and more material-efficient than moment frames, which rely on bending of beams and columns." },
  { id: "S02", cat: "struct", q: "In a simply supported beam under a uniformly distributed load, the maximum bending moment occurs at the:",
    options: ["Supports", "Quarter span", "Midspan", "Free end"], answer: 2,
    explain: "For a simply supported beam with a uniform load, the bending-moment diagram is parabolic and peaks at midspan, where it equals wL\u00b2/8." },
  { id: "S03", cat: "struct", q: "A load applied within the ___ of a column cross-section produces compression across the whole section with no tension.",
    options: ["Centroid", "Kern", "Neutral axis", "Shear center"], answer: 1,
    explain: "The kern (or core) is the central region of a section. As long as the resultant load stays within it, the entire section remains in compression\u2014important for masonry and concrete that resist little tension." },
  { id: "S04", cat: "struct", q: "The ratio of a column's effective length to its least radius of gyration is called the:",
    options: ["Aspect ratio", "Slenderness ratio", "Poisson's ratio", "Load factor"], answer: 1,
    explain: "The slenderness ratio (KL/r) governs how a column fails: low values fail by crushing, high values fail by buckling. It is the key parameter in column design." },
  { id: "S05", cat: "struct", q: "When soil near the surface has low bearing capacity and loads are heavy, the most appropriate foundation transfers load to deeper, firmer strata using:",
    options: ["Isolated footings", "A pile foundation", "A strip footing", "A grade beam"], answer: 1,
    explain: "Pile foundations carry loads past weak surface soils to competent strata or rock through end-bearing and skin friction, making them suited to heavy loads on poor soil." },
  { id: "S06", cat: "struct", q: "A truss is an efficient long-span structure mainly because its members carry loads as:",
    options: ["Bending moments", "Axial tension and compression", "Torsion", "Shear only"], answer: 1,
    explain: "An ideal truss is pin-connected so its members carry pure axial force\u2014tension or compression\u2014rather than bending, allowing slender members to span large distances economically." },
  { id: "S07", cat: "struct", q: "In seismic design, the lateral force a building must resist is most directly proportional to the building's:",
    options: ["Height only", "Mass (weight)", "Window area", "Roof slope"], answer: 1,
    explain: "Seismic base shear is proportional to the structure's mass (F = ma). Heavier buildings attract larger inertial forces, which is why reducing mass is a key seismic strategy." },
  { id: "S08", cat: "struct", q: "A structural system in which floor plates are suspended by hangers from a central core or mast is known as a:",
    options: ["Cantilever structure", "Suspended (hung) structure", "Space frame", "Shear-wall structure"], answer: 1,
    explain: "In a suspended structure, floors hang in tension from a strong core or mast, freeing the ground plane of columns\u2014used in buildings like the former BMW and HSBC headquarters." },

  /* ---------------- History & Theory ---------------- */
  { id: "H01", cat: "hist", q: "The principle 'form follows function' is most closely associated with which architect?",
    options: ["Le Corbusier", "Louis Sullivan", "Frank Lloyd Wright", "Mies van der Rohe"], answer: 1,
    explain: "Louis Sullivan, the 'father of the skyscraper,' coined 'form ever follows function,' arguing a building's shape should derive from its purpose. Wright, his prot\u00e9g\u00e9, later refined the idea." },
  { id: "H02", cat: "hist", q: "The minimalist dictum 'less is more' is attributed to:",
    options: ["Walter Gropius", "Mies van der Rohe", "Adolf Loos", "Philip Johnson"], answer: 1,
    explain: "Ludwig Mies van der Rohe popularised 'less is more,' expressing the reductive, structurally honest aesthetic of the International Style." },
  { id: "H03", cat: "hist", q: "The Bauhaus school, founded in 1919, was established by:",
    options: ["Walter Gropius", "Hannes Meyer", "Marcel Breuer", "Wassily Kandinsky"], answer: 0,
    explain: "Walter Gropius founded the Bauhaus in Weimar in 1919, uniting craft and fine art and shaping modern design education worldwide." },
  { id: "H04", cat: "hist", q: "The columns of the Parthenon are predominantly of which Greek classical order?",
    options: ["Doric", "Ionic", "Corinthian", "Tuscan"], answer: 0,
    explain: "The Parthenon's exterior colonnade is Doric\u2014the oldest and sturdiest Greek order, identified by its plain capital and fluted shaft with no base." },
  { id: "H05", cat: "hist", q: "Flying buttresses, ribbed vaults, and pointed arches are hallmarks of which architectural style?",
    options: ["Romanesque", "Gothic", "Baroque", "Renaissance"], answer: 1,
    explain: "Gothic architecture used pointed arches, ribbed vaults, and flying buttresses to channel loads outward, enabling tall, light-filled cathedrals with large stained-glass windows." },
  { id: "H06", cat: "hist", q: "The essay 'Ornament and Crime,' arguing against decorative excess, was written by:",
    options: ["Adolf Loos", "Otto Wagner", "Antoni Gaud\u00ed", "Victor Horta"], answer: 0,
    explain: "Adolf Loos's 1908 essay 'Ornament and Crime' equated unnecessary ornament with cultural regression, anticipating the stripped aesthetic of Modernism." },
  { id: "H07", cat: "hist", q: "The Villa Savoye, which embodies the 'Five Points of a New Architecture,' was designed by:",
    options: ["Le Corbusier", "Gerrit Rietveld", "Richard Neutra", "Alvar Aalto"], answer: 0,
    explain: "Le Corbusier's Villa Savoye (1931) demonstrates his Five Points: pilotis, free plan, free fa\u00e7ade, horizontal windows, and a roof garden." },
  { id: "H08", cat: "hist", q: "The central circular opening at the apex of the Roman Pantheon's dome is called the:",
    options: ["Lantern", "Oculus", "Cupola", "Pendentive"], answer: 1,
    explain: "The oculus is the 8-metre opening at the crown of the Pantheon's coffered dome\u2014its only light source and a structural device that reduces the dome's weight." },

  /* ---------------- Professional Practice ---------------- */
  { id: "P01", cat: "prac", q: "The National Building Code of the Philippines is legally known as:",
    options: ["Republic Act 9266", "Presidential Decree 1096", "Batas Pambansa 344", "Republic Act 6541"], answer: 1,
    explain: "Presidential Decree No. 1096 (1977) is the National Building Code of the Philippines, governing design, construction, use, and occupancy of buildings nationwide." },
  { id: "P02", cat: "prac", q: "The law that regulates the practice of architecture in the Philippines is:",
    options: ["RA 9266 \u2014 The Architecture Act of 2004", "RA 1378", "PD 223", "RA 544"], answer: 0,
    explain: "Republic Act 9266, the Architecture Act of 2004, governs the licensure and practice of architecture and created the Professional Regulatory Board of Architecture." },
  { id: "P03", cat: "prac", q: "Under the National Building Code, the minimum width of an exit corridor serving an occupant load exceeding 50 persons is:",
    options: ["0.90 metres", "1.10 metres", "1.20 metres", "1.50 metres"], answer: 2,
    explain: "Corridors serving more than 50 occupants must be at least 1.20 m wide to preserve required egress capacity under the Building and Fire Codes." },
  { id: "P04", cat: "prac", q: "The integrated and accredited professional organization of architects in the Philippines is the:",
    options: ["Philippine Institute of Architects", "United Architects of the Philippines", "League of Philippine Architects", "Council of Architects"], answer: 1,
    explain: "The United Architects of the Philippines (UAP) is the duly accredited Integrated and Bona Fide Professional Organization (IAPO) of Filipino architects." },
  { id: "P05", cat: "prac", q: "Unless the contract states otherwise, the instruments of service\u2014the drawings and specifications\u2014are owned by the:",
    options: ["Client / owner", "Contractor", "Architect", "Building official"], answer: 2,
    explain: "The architect retains ownership and copyright of the instruments of service. The client receives a license to use them for the specific project only." },
  { id: "P06", cat: "prac", q: "Under UAP guidelines, the architect's basic services are most commonly compensated as a percentage of the:",
    options: ["Lot area", "Project construction cost", "Gross floor area", "Architect's overhead"], answer: 1,
    explain: "The standard method of compensation for basic services is a percentage of the project construction cost, scaled to the project type and complexity." },
  { id: "P07", cat: "prac", q: "The document issued by the local building official that legally authorises construction to begin is the:",
    options: ["Occupancy permit", "Building permit", "Locational clearance", "Certificate of completion"], answer: 1,
    explain: "A building permit, issued by the Office of the Building Official after plan review, is required before any construction, alteration, or repair may legally start." },
  { id: "P08", cat: "prac", q: "Accessibility provisions for persons with disabilities in Philippine buildings are governed by:",
    options: ["BP 344 (Accessibility Law)", "PD 1096", "RA 9266", "RA 11058"], answer: 0,
    explain: "Batas Pambansa Bilang 344, the Accessibility Law, mandates barrier-free facilities such as ramps, accessible toilets, and tactile guides for persons with disabilities." },

  /* ---------------- Building Utilities ---------------- */
  { id: "U01", cat: "util", q: "The recommended minimum slope for a 100 mm horizontal sanitary drainage pipe is approximately:",
    options: ["0.5% (1:200)", "1% (1:100)", "2% (1:50)", "5% (1:20)"], answer: 2,
    explain: "A 2% slope (about 1/4 inch per foot, or 1:50) lets solids and liquids flow together at a self-cleansing velocity without leaving solids behind." },
  { id: "U02", cat: "util", q: "The primary purpose of a plumbing fixture trap is to:",
    options: ["Increase water pressure", "Prevent sewer gases from entering the building", "Filter the water", "Reduce noise"], answer: 1,
    explain: "A trap holds a water seal that blocks foul sewer gases from rising into occupied spaces while still allowing wastewater to drain." },
  { id: "U03", cat: "util", q: "A water-distribution scheme that feeds fixtures by gravity from an elevated roof tank is called a:",
    options: ["Upfeed system", "Downfeed system", "Pneumatic system", "Direct-pressure system"], answer: 1,
    explain: "In a downfeed system, pumps fill an elevated tank and gravity supplies the fixtures below, giving steady pressure and a reserve during power or pump failure." },
  { id: "U04", cat: "util", q: "In an electrical installation, the device that automatically interrupts a circuit during an overcurrent or short circuit is the:",
    options: ["Transformer", "Circuit breaker", "Capacitor", "Busbar"], answer: 1,
    explain: "A circuit breaker protects conductors and equipment by tripping when current exceeds a safe limit, and it can be reset after the fault is cleared." },
  { id: "U05", cat: "util", q: "The recommended illuminance level for general office work is approximately:",
    options: ["100 lux", "300\u2013500 lux", "1000 lux", "50 lux"], answer: 1,
    explain: "General office and reading tasks call for roughly 300\u2013500 lux to support visual comfort and productivity without glare or excessive energy use." },
  { id: "U06", cat: "util", q: "A wet standpipe with fire-hose connections is a component of a building's:",
    options: ["Sanitary system", "Fire-protection system", "HVAC system", "Storm-drainage system"], answer: 1,
    explain: "Standpipes are part of the active fire-protection system, delivering water to hose outlets on each floor so occupants or firefighters can fight a fire quickly." },
  { id: "U07", cat: "util", q: "The performance of a building's ventilation is commonly expressed in:",
    options: ["Lux per square metre", "Air changes per hour (ACH)", "Decibels", "Lumens"], answer: 1,
    explain: "Ventilation effectiveness is measured in air changes per hour\u2014the number of times the air volume of a space is replaced each hour\u2014guiding HVAC and IAQ design." },

  /* ---------------- Architectural Design ---------------- */
  { id: "D01", cat: "design", q: "Anthropometrics, a key input to space planning, is the study of:",
    options: ["Building acoustics", "Human body measurements", "Soil behaviour", "Daylight angles"], answer: 1,
    explain: "Anthropometrics studies the dimensions and proportions of the human body, informing ergonomic clearances, furniture sizes, and circulation widths." },
  { id: "D02", cat: "design", q: "For comfortable residential stairs, the ideal riser height is closest to:",
    options: ["100 mm", "175 mm", "230 mm", "300 mm"], answer: 1,
    explain: "A riser of about 150\u2013180 mm (with a tread of ~250\u2013300 mm) yields a comfortable, safe stair. Around 175 mm is a common target for residential use." },
  { id: "D03", cat: "design", q: "The core aim of Universal Design is to create environments that are:",
    options: ["Cheapest to build", "Usable by all people regardless of age or ability", "Strictly minimalist", "Reserved for accessibility ramps only"], answer: 1,
    explain: "Universal Design seeks spaces and products usable by the widest range of people\u2014of any age, size, or ability\u2014without the need for adaptation or specialised design." },
  { id: "D04", cat: "design", q: "In schematic planning, a bubble diagram is used mainly to study:",
    options: ["Structural grid", "Spatial relationships and adjacencies", "Exact dimensions", "Material finishes"], answer: 1,
    explain: "Bubble diagrams loosely represent spaces as circles and their links, letting designers test adjacencies, zoning, and circulation before committing to dimensioned plans." },
  { id: "D05", cat: "design", q: "Under BP 344, the minimum clear width of an accessible ramp is:",
    options: ["0.90 m", "1.00 m", "1.20 m", "1.50 m"], answer: 2,
    explain: "The Accessibility Law requires accessible ramps to be at least 1.20 m wide, with a maximum slope of 1:12, to safely accommodate wheelchair users." },
  { id: "D06", cat: "design", q: "The 'service core' of a typical high-rise building usually contains:",
    options: ["Tenant offices", "Elevators, stairs, restrooms, and MEP shafts", "Parking", "Retail units"], answer: 1,
    explain: "A central service core groups vertical circulation (lifts and stairs), toilets, and mechanical/electrical/plumbing shafts, freeing the perimeter for usable, day-lit floor space." },
  { id: "D07", cat: "design", q: "Proper orientation of a building on its site is studied primarily to optimise:",
    options: ["Foundation depth", "Sun, wind, and natural light", "Paint colour", "Property tax"], answer: 1,
    explain: "Orientation is a passive-design strategy: aligning a building to sun path and prevailing winds reduces heat gain, improves daylight, and lowers energy demand." },

  /* ---------------- Building Materials ---------------- */
  { id: "M01", cat: "mats", q: "The chemical reaction by which cement combines with water and hardens is called:",
    options: ["Oxidation", "Hydration", "Carbonation", "Vulcanisation"], answer: 1,
    explain: "Hydration is the exothermic reaction between cement and water that forms crystalline bonds, giving concrete its strength as it cures." },
  { id: "M02", cat: "mats", q: "Tempered (toughened) glass is specified for doors and low panels chiefly because it:",
    options: ["Is cheaper than annealed glass", "Breaks into small blunt fragments when shattered", "Cannot break", "Blocks all sunlight"], answer: 1,
    explain: "Tempered glass is heat-treated to be much stronger and, when broken, crumbles into small relatively harmless granules instead of sharp shards\u2014hence its use as safety glazing." },
  { id: "M03", cat: "mats", q: "The water-cement ratio of a concrete mix most directly affects its:",
    options: ["Colour", "Compressive strength", "Weight only", "Set time only"], answer: 1,
    explain: "A lower water-cement ratio generally produces stronger, denser, more durable concrete; excess water increases workability but reduces strength and increases porosity." },
  { id: "M04", cat: "mats", q: "Seasoning of timber before use is carried out mainly to:",
    options: ["Add colour", "Reduce its moisture content", "Increase its weight", "Make it fire-proof"], answer: 1,
    explain: "Seasoning lowers timber's moisture content to equilibrium with its environment, reducing shrinkage, warping, decay, and improving strength and finish adhesion." },
  { id: "M05", cat: "mats", q: "Curing of freshly placed concrete is necessary primarily to:",
    options: ["Speed up demolition", "Maintain moisture for proper strength gain", "Change its colour", "Reduce its cost"], answer: 1,
    explain: "Curing keeps concrete adequately moist and at a favourable temperature so hydration can continue, which is essential for the concrete to reach its design strength and durability." },
  { id: "M06", cat: "mats", q: "Steel is commonly used to reinforce concrete because the two materials:",
    options: ["Have the same colour", "Complement each other\u2014steel in tension, concrete in compression", "Both resist fire equally", "Are equally light"], answer: 1,
    explain: "Concrete is strong in compression but weak in tension; steel is strong in tension. Reinforced concrete places steel where tension occurs, combining their strengths." },
  { id: "M07", cat: "mats", q: "A material's ability to return to its original shape after a load is removed is its:",
    options: ["Plasticity", "Elasticity", "Brittleness", "Ductility"], answer: 1,
    explain: "Elasticity is the property by which a material deforms under load and recovers its original shape once the load is removed, up to its elastic limit." },
];
